force-app/main/default/objects/Beer__c/Beer__c.object-meta.xml
<CustomObject>
    <description>Represents a beer that is brewed by this company. Contains information such as its taste characteristics, price, etc.</description>
    <label>Beer</label>
    <nameField>
        <label>Beer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Beer__c/fields/On_Tap__c.field-meta.xml
<CustomField>
    <fullName>On_Tap__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the beer is on tap or not.</description>
    <label>On Tap</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Review__c/Customer_Review__c.object-meta.xml
<CustomObject>
    <description>Feedback from a customer regarding a particular Beer.</description>
    <label>Customer Review</label>
    <nameField>
        <label>Customer Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Review__c/fields/Beer__c.field-meta.xml
<CustomField>
    <fullName>Beer__c</fullName>
    <description>Lookup to the beer which the feedback is meant for</description>
    <label>Beer</label>
    <referenceTo>Beer__c</referenceTo>
    <relationshipLabel>Customer Reviews</relationshipLabel>
    <relationshipName>Customer_Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Customer_Review__c/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <description>Email of the customer submitting the feedback</description>
    <label>Customer Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Customer_Review__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <description>Full or partial name of the customer who submitted the feedback</description>
    <label>Customer Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Review__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <description>Rating scale for customers to rate beers</description>
    <label>Rating</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsatisfactory - Would Not Recommend or Purchase Again</fullName>
            </value>
            <value>
                <fullName>Average - Would Not Purchase Again</fullName>
            </value>
            <value>
                <fullName>Good - Would Purchase Again</fullName>
            </value>
            <value>
                <fullName>Great - Would Recommend and Purchase Again</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/vbc_FormCmpController.cls
/**  Created by alec@gscloudsolutions on 21.08.18  */

public with sharing class vbc_FormCmpController {
    
    private static final String DEFAULT_USER_ERR_MSG = 
        'Whoops, something went wrong! Please refresh the page and try again.';

    /**
     * Wrapper class as a workaround because Schema.PicklistEntry is not AuraEnabled
     */
    public class LtngSelect {
        public String label {get;set;}
        public String value {get;set;}
        
        public LtngSelect(Schema.PicklistEntry picklistEntry) {
            this.label = picklistEntry.getLabel();
            this.value = picklistEntry.getValue();
        }
    }

    /**
     * Inserts a customer review. Performs server side validation on the review to ensure all
     * required fields are populated. @throws an AuraHandledException otherwise
     */
    @AuraEnabled
    public static void submitReview(Customer_Review__c review) {

        // Perform server side validation
        Set<String> requiredFieldSet = new Set<String> {
            'Customer_Name__c', 'Customer_Email__c', 'Rating__c', 'Beer__c'
        };
        Boolean hasRequiredFields = true;
        if (review != null) {
            for (String field : requiredFieldSet) {
                hasRequiredFields = 
                    hasRequiredFields && String.isNotEmpty(String.valueOf(review.get(field)));
            }
        } 
        if (review == null || !hasRequiredFields) {
            System.debug(LoggingLevel.INFO, 'Customer tried to submit form without all required fields');
            throw new AuraHandledException(DEFAULT_USER_ERR_MSG);
        }

        // Insert the review
        try {
            insert review;
        } catch (Exception e) {
            System.debug(LoggingLevel.ERROR, e.getMessage());
            throw new AuraHandledException(DEFAULT_USER_ERR_MSG);
        }

    }

    /**
     * Retrieves all beer records that are marked as being on tap
     */
    @AuraEnabled
    public static List<Beer__c> getBeersOnTap() {
        return [SELECT Id, Name FROM Beer__c WHERE On_Tap__c = true];
    }

    /**
     * Gets all the active picklist values for Customer_Review__c.Review__c and returns them
     * in the LtngSelect wrapper class
     */
    @AuraEnabled
    public static List<LtngSelect> getRatingPicklistValues() {
        List<Schema.PicklistEntry> picklistEntryList = 
            Customer_Review__c.Rating__c.getDescribe().getPicklistValues();
        List<LtngSelect> ltngSelectList = new List<LtngSelect>();
        for (Schema.PicklistEntry picklistEntry : picklistEntryList) {
            if (picklistEntry.isActive()) {
                ltngSelectList.add(new LtngSelect(picklistEntry));
            }
        }
        return ltngSelectList;
    }

}